### ISSUE TITLE
How to get the results of the changeset ?

### ISSUE THREAD

**Issue by Moxide** [kaliber5/ember-bootstrap-changeset-validations#1]
Hello,
Starting from your dummy app, I'm trying to get access to the results of the changeset from the controller's `submit()` function, to run `changeset.execute` for instance.

So, instead of using the `changeset` template helper: 
```
{{#bs-form model=(changeset model validation) action=(action "submit") invalid=(action "invalid")}}
    {{bs-form-element label="Name" property="name"}}
    {{bs-button type="primary" buttonType="submit" defaultText="Submit"}}
{{/bs-form}}
```
 I'm trying to create the changeset from javascript:

The template :
```
{{#bs-form model=changeset action=(action "submit") invalid=(action "invalid")}}
    {{bs-form-element label="Name" property="name"}}
    {{bs-button type="primary" buttonType="submit" defaultText="Submit"}}
{{/bs-form}}
```
and in the controller :
```
  init() {
    this.changeset = new Changeset(this.get('model'), this.get('validation'));
  },
```

But if I do so, the validations seems to be ignored (textfields always validate).

What is the correct way to get the changeset ? It would be great if the changeset could be returned as a parameter (ie `submit(changeset) {}`), but I don't know how to do this.

Thanks in advance !

**Comment by simonihmig** [comment]
There are two things touched by your issue:

1. getting the model from the submit action: indeed it would be useful to get the form's model as a parameter of the submit action. Makes less sense when setting the model directly on the `bs-form` as you could do it like this: `{{#bs-form model=model action=(action "submit" model)}}`. But when using the `changeset` helper you have no reference to the `Changeset` object created by the helper. So calling the submit action and passing the model (in this case the `Changeset`) to it would make sense. Will add an issue to `ember-bootstrap` to add this.

2. At first look I would have guessed that the way you changed the example to create the `Changeset` by JavaScript should work. But indeed it does not, just tested it. It is not ember-bootstrap's fault, though. 

It seems you cannot create the `Changeset` as it was documented on the ember-changeset github repo when using ember-changeset-validations! It needs a `lookupValidator` function to be applied on the validation object, to convert the validation POJO into a function as expected by `Changeset`. You can see this in the `changeset` helper, that is overriden by ember-changeset-validations to add this, see https://github.com/DockYard/ember-changeset-validations/blob/master/addon/helpers/changeset.js#L10. Unfortunately this is not documented on the ember-changeset-validations page.

I updated the dummy app to match your example and added the necessary change:
https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/master/tests/dummy/app/controllers/application.js#L27. Now it works again as expected!

**Comment by Moxide** [comment]
Thank you **very** much for your exhaustive and lightning-fast answer !
When digging in the code, I was looking at the wrong place and completely missed the overridden `changeset` helper :-(
Adding the `lookupValidator` function works at once, of course :-)
But getting the changeset in the `submit` will be even nicer ;-)

I naïvely tried to override the `submit` function in `ember-bootstrap-changeset-validations
`'s `bs-form.js` like this :

```
submit(e) {
    if (e) {
      e.preventDefault();
    }

    this.sendAction('before');

    if (!this.get('hasValidator')) {
      return this.sendAction();
    } else {
      let validationPromise = this.validate(this.get('model'));
      if (validationPromise && validationPromise instanceof Ember.RSVP.Promise) {
        validationPromise.then((r) => this.sendAction('action', this.get('model'), r), (err) => {
          this.get('childFormElements').setEach('showValidation', true);
          return this.sendAction('invalid', this.get('model'), err);
        });
      }
    }
  },
```
and it seems to work, we get the model as parameter.
This way, one doesn't need to create a `changeset` by hand, the changeset helper is enough.

**Comment by simonihmig** [comment]
Yes, I would add something like that to ember-bootstrap itself. You might want to subscribe to #126, as soon as that is implemented within ember-bootstrap, you can drop your override...

**Comment by Moxide** [comment]
Done ;-)
Thanks again.
