### ISSUE TITLE
Validations trigger on fields that aren't present in the form.

### ISSUE THREAD

**Issue by sumeetattree** [kaliber5/ember-bootstrap-changeset-validations#11]
Not sure if this is the right place.

I have a user model with `name`, `password`, `passwordConfirmation` fields. I've commented out `password` and `passwordConfirmation` from the form but the validations still fail on the `password` field in the changeset.

Expected Behavior:
Validations should only run on the fields present in the form.

As a side note, I've experienced the same issue with the `ember-bootstrap-cp-validations`. Validations seem to fire on fields that are absent from the form but have validations defined on them.

**Comment by simonihmig** [comment]
Sorry for the late answer. But I don't think this can be changed, and not even sure it *should* be changed. I know from other validation libraries (server-side) the concept of groups or contexts, that let you change the rules of validation for a given object (say for "create" a user needs to have a plaintext password, but not for the "edit" context). But AFAIK this does not exist here, neither in the changeset addon nor cp-validations...

And the form itself just asks the model if it's valid, so no way to change the validation logic there.

What I have done in the past is to define validations on a component (that was using `ember-bootstrap-cp-validations`), in this case we had a `user-form-create` and `user-form-edit` component (which use `bs-form` and pass the component as the model, e.g. `{{#bs-form model=this as |form|}}...`. Maybe that approach works for you?

Closing this for now. Feel free to reopen if you believe there should be a change in this repo!
