### ISSUE TITLE
Execute changes in changeset upon successful validation?

### ISSUE THREAD

**Issue by swquinn** [kaliber5/ember-bootstrap-changeset-validations#3]
Hi, I started looking at this add-on because I was already using `ember-bootstrap` and wanted to add validation to my forms using [`ember-changeset`](https://github.com/DockYard/ember-changeset). Unless I am doing something wrong, it seems like I need to manually execute the changeset with `changeset.execute()` if I want to apply the changes to the data model that the changeset wraps.

I understand that I can call `save()` etc. on the changeset object, but until recently where the model for the form submission wasn't being passed along to the action I was working with my model references directly. It seems like it would it make sense to me to automatically execute the changes (provided that they are valid) following validation but before executing the submit action.

If this sounds like it would be a good idea, I can work on a pull request for it. If not, can you advise on a recommended best practice?

**Comment by simonihmig** [comment]
@swquinn Sorry for the super late answer. Somehow I missed the GitHub notification.

I see it requires a bit more work to get back a reference to the changeset. That was one of the reasons to pass the model from the `onSubmit` action. I think you could also use the `{{#with}}` helper in your template to do so.

However I feel it is beyond the scope of `bs-form` to call `save()`, as it is just a generic UI component and does not know it what context it is used, i.e. in many situations it might not be appropriate to directly call `save()`, as the user of that component knows what should actually happen on submit. Also the `bs-form` of ember-bootstrap-changeset-validations that extends the base `bs-form` of ember-bootstrap should not change the behavior of the latter, as that would be inconsistent and probably unexpected.

I would recommend wrapping the form in a application specific form component, like `user-form`, which knows about the application specific context and could be responsible to actually call `save()`.
