### ISSUE TITLE
Ember Bootstrap v4 support

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap-changeset-validations#32]
This addon should work with that version, but we do not explicitly state that, and also don't test it.

We could either:
* add an additional test scenario for v4 (or add another dimensions to the test matrix to test v4 w/ all existing scenarios / Ember versions)
* drop support for v3 and release a new major

@jelhan thoughts?

**Comment by jelhan** [comment]
I think dropping support for Ember Bootstrap v3 is fine. Having to support multiple versions in parallel increases complexity. It only makes sense in my opinion if two different version of a library are used and supported in parallel (e.g. different ember versions). But as we don't consider Ember Bootstrap v3 as supported anymore I think it's fine to ask everyone to upgrade.

**Comment by jelhan** [comment]
Dropped support for Ember Bootstrap <= v4.4 in [v4.0.0](https://github.com/kaliber5/ember-bootstrap-changeset-validations/releases/tag/v4.0.0) released today.
