### ISSUE TITLE
Validation on init causing double render error.

### ISSUE THREAD

**Issue by arenoir** [kaliber5/ember-bootstrap-changeset-validations#6]
The observer in the bs-form that validates the model on init causes a double render in some cases.  Perhaps it should be configurable?   Specifically if you render a form in a bs-modal.body and reference the changeset in the bs-model.header or footer.

**Comment by simonihmig** [comment]
Thanks for mentioning. Do you have some example code that reliably reproduces that issue?

**Comment by arenoir** [comment]
Yes I have an application that is experiencing this issue.  I will try a recreate it with a twiddle.  I have removed the on init observer in my application as I believe it is redundant.  The attributes are validated on mutation and the whole model is validated before submit.

**Comment by nkgm** [comment]
@arenoir would I be right in assuming you have bindings to `changeset.isDirty`? 

This is a nasty one as `changeset#validate` will actually `notifyPropertyChange(CHANGES)` **always, regardless of actual changes**, which will fire further updates on `isPristine` and in turn `isDirty`. Hence, anything bound on `changeset.isDirty` will fire twice in the render cycle. I'm guessing using an observer in `bs-form#_initValidation` doesn't help either, but this is more likely `ember-changeset`'s fault for preemptively calling `notifyPropertyChange(CHANGES)`.

**Comment by arenoir** [comment]
https://github.com/kaliber5/ember-bootstrap-changeset-validations/pull/13
