### ISSUE TITLE
[help] How do you access the `changeset` in the template?

### ISSUE THREAD

**Issue by thornomad** [kaliber5/ember-bootstrap-changeset-validations#7]
Hi there - am new to Ember and struggling with this concept.  I want to access the `changeset` inside my handlebars template ... like so

```handlebars
{{#bs-form model=(changeset person PersonValidations) onSubmit=(action "submit") as |form|}}

  {{#if changeset.isInvalid}}  invalid ! {{else}}  well done. {{/if}}

  {{form.element controlType="text" label="First Name" placeholder="First Name" property="firstName"}}
  {{form.element controlType="text" label="Last Name" placeholder="Last Name" property="lastName"}}
  {{form.element controlType="email" label="Email" placeholder="Email" property="email"}}
  {{bs-button defaultText="Submit" type="primary" buttonType="submit"}}
{{/bs-form}}
```

Obviously, `changeset` isn't populated cuz it's being passed dynamically.

I tried to create the changeset at the component level ... but even though it appears to do the same thing on the console the actual validations aren't working.

```javascript
import Ember from 'ember';
import Changeset from 'ember-changeset';
import PersonValidations from '../../../validations/person';

export default Ember.Component.extend({
  init(...args) {
    this._super(...args);
    const model = this.get('person');
    this.changeset = new Changeset(model, PersonValidations);
  },
  PersonValidations,
});
```

Can you help point me in the right direction?

**Comment by jimmyjlli** [comment]
I think you need to call the lookupValidator manually when creating changeset in js, as shown in https://github.com/DockYard/ember-changeset-validations

For example,
`
import Ember from 'ember';
import Changeset from 'ember-changeset';
**import lookupValidator from 'ember-changeset-validations';**
import PersonValidations from '../../../validations/person';

export default Ember.Component.extend({
  PersonValidations,

  init(...args) {
    this._super(...args);
    const model = this.get('person');
    this.changeset = new Changeset(model, **lookupValidator**(PersonValidations));
  }
});
`

**Comment by simonihmig** [comment]
I think @jimmyjlli's comment (thanks for chiming in!) should fix your problem. If not, feel free to reopen this issue! Closing for now...

**Comment by thornomad** [comment]
Thanks for your help @jimmyjlli - I have been traveling but will implement soon.
